version: "3"

services:
  hub:
    env_file:
      - env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JUPYTERHUB_VERSION: latest
    restart: always
    image: jupyterhub-oauth
    container_name: jupyterhub-oauth
    networks:
      - jupyterhub-network
    volumes:
      # The JupyterHub configuration file
      - "./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro"
      # Bind Docker socket on the host so we can connect to the daemon from
      # within the container
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      - "./admins:/srv/oauthenticator/admins:ro"
      # Bind Docker volume on host for JupyterHub database and cookie secrets
      - "jupyterhub-data:/data"
      - "../rooms_config.yaml:/rooms_config.yaml"
    ports:
      - "8000:8000"
    environment:
      # All containers will join this network
      DOCKER_NETWORK_NAME: jupyterhub-network
      # JupyterHub will spawn this Notebook image for users
      # for local
      # DOCKER_NOTEBOOK_IMAGE: collab_learning_extension
      # for remote
      DOCKER_NOTEBOOK_IMAGE: ghcr.io/eth-peach-lab/collaborative-learning-extension-jupyter:v0.2.1
      # Notebook directory inside user image
      DOCKER_NOTEBOOK_DIR: /home/jovyan/work
volumes:
  jupyterhub-data:
networks:
  jupyterhub-network:
    name: jupyterhub-network